vich_uploader:
    db_driver: orm

    mappings:
        home:
            uri_prefix: /images/home
            upload_destination: '%kernel.project_dir%/public/images/home'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer    
        slider:
            uri_prefix: /images/slider
            upload_destination: '%kernel.project_dir%/public/images/slider'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
